### ISSUE TITLE
Page how do you feel

### ISSUE THREAD

**Issue by dsernahiguita** [FightCOVID19/webapp#15]

**Comment by dsernahiguita** [comment]
solve with the pull request https://github.com/FightCOVID19/webapp/pull/16

**Comment by JuanSeBestia** [comment]
@dsernahiguita about the line https://github.com/FightCOVID19/webapp/blob/master/src/pages/howDoYouFeel/HowDoYouFeel.scss#L15 you are putting max-width in 400px

I really happy with your work but, I think the app would be mobile-first, but supportable in all screens/ widths, what do you think?

**Comment by dsernahiguita** [comment]
Hi Juan :)
thanks for your comments..
I thought we should keep the design format which is  portrait format :).
You are right we should support all the screens/width but if we don't have defined width on a landscape screen, the webapp doesn't looks as beautiful as in the original design..
I have two proposals and you can tell me which one you prefer

1. I can add a util library to identify if the screen is type landscape or portrait, if the type is portrait I will not defined the width (to use all the width of the screen), if it is landscape I will defined the width in order that the web app is placed in the middle.

2. I will remove the width without to identify the screen type.

only let me know what do you prefer.

Best greetings
Diana

**Comment by JuanSeBestia** [comment]
I like the first, but I think that I don't have the correct rights to answer that proposal, maybe is better scale this proposal

**Comment by JuanSeBestia** [comment]
FYI: Rigth now we have two versión of pages

The issue is happening, because not have mocks for Desktop size 

**with width-max**
![image](https://user-images.githubusercontent.com/7362688/78706819-4fc68980-78d5-11ea-80f6-bb0ae3704268.png)

**with full-width**

![image](https://user-images.githubusercontent.com/7362688/78706924-7f759180-78d5-11ea-8aee-fe0dfa6402b3.png)

Please help us adding your point of view
